[package]
name = "rust_packaging_example"
version = "0.1.0"
description = "Example rust program used for generating packages (rpm, deb, etc.)"
authors = ["Anup Dhamala <anupdhml+git@gmail.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]

[package.metadata.rpm.cargo]
buildflags = ["--release"]

[package.metadata.rpm.targets]
rust_packaging_example = { path = "/usr/bin/rust_packaging_example" }
