[package]
name = "rust_packaging_example"
version = "0.1.0"
authors = ["Anup Dhamala <anupdhml+git@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
