#!/bin/sh

# exit the script when a command fails
set -o errexit

adduser --system --group --no-create-home --quiet rust

mkdir -p /var/log/rust-packaging-example
chown -R rust:rust /var/log/rust-packaging-example
