# build via:
#   docker build --network host -t anupdhml/example-builder:x86_64-unknown-linux-gnu --build-arg RUST_VERSION=1.43.1 -f ./Dockerfile.x86_64-unknown-linux-gnu .

# latest stable version as of May 22, 2020
#ARG RUST_VERSION="1.43.1"
ARG RUST_VERSION

# via https://hub.docker.com/_/rust
FROM rust:${RUST_VERSION}-buster

# TODO base this image on vanilla ubuntu (or debian) and install rust like this
# we may not need to do this with cross actually, since cross shares cargo/rustc from host
#
# for ref: https://github.com/rust-lang/docker-rust/blob/master/1.43.1/buster/Dockerfile#
#RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rustup-init.sh \
#    #&& sh rustup-init.sh -y --no-modify-path \
#    && sh rustup-init.sh -y \
#    && rm rustup-init.sh
#
#ENV PATH="/root/.cargo/bin:${PATH}"

COPY shared/install_dependencies_debian.sh /
RUN /install_dependencies_debian.sh
